# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Algorithms and Software Engineering Notes
email: 
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://george24601.github.io" # the base hostname & protocol for your site
github_username:  george24601

footer-links:
  github: george24601
  linkedin: george24601

# Build settings
markdown: kramdown

gems:
  - jekyll-paginate

paginate: 10

paginate_path: "/blog/page:num/"
